### ISSUE TITLE
BlackLists

### ISSUE THREAD

**Issue by DannyBG** [PaulTDD-MC/BanManager#1]
I want /blacklist (playername) (reason) and all blacklists are saved in other file because all player bans are saved in one file and when i decide to reset the ban list. I will just del the file and it will be easy. But someone is blacklisted that means that he never will be back in the server.Because if i want to blacklist players with default ban command i need to write in reason that is blacklisted and when i reset banlist i need to del every ban by hand not the whole file. Because i will reset blacklisted players too

**Comment by PaulTDD-MC** [comment]
Help me out here, why whould you remove all banned players?

**Comment by DannyBG** [comment]
Because sometimes servers resets ban lists

**Comment by PaulTDD-MC** [comment]
Hmm, okay. I'll look into it.

**Comment by PaulTDD-MC** [comment]
Hey @DannyBG,
I looked into it, but it doesn't really seem nessesary. So I won't make it.
Sorry, you whould have to do it by hand. The tab-completion method in spigot is really handy to use in these cases.
Greetings.
